name: tabeling
description: "A Project for Opensource Software Class. Clone Coding project of Tabeling Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0-30.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_naver_map: ^1.4.1+1
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/jsons/
    - assets/lottie/
    - assets/splash/
    - lib/data/business_data.json
    - lib/data/menu_data.json
    - lib/data/user_data.json
    - lib/data/voc_data.json
    - lib/data/business_registration_list.json


flutter_native_splash:
  background_image: assets/splash/splash_background.jpg
  image: assets/images/login_symbol_big.png
  fullscreen: true

  android_12:
    color: "#ffffff"
    image: assets/images/login_symbol_big.png
